/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ProtectedFriendsIndexRouteImport } from './routes/_protected/friends/index'
import { Route as ProtectedChatsIndexRouteImport } from './routes/_protected/chats/index'
import { Route as ProtectedChatsConversationIdRouteImport } from './routes/_protected/chats/$conversationId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedFriendsIndexRoute = ProtectedFriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatsIndexRoute = ProtectedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatsConversationIdRoute =
  ProtectedChatsConversationIdRouteImport.update({
    id: '/chats/$conversationId',
    path: '/chats/$conversationId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/': typeof AuthIndexRoute
  '/chats/$conversationId': typeof ProtectedChatsConversationIdRoute
  '/chats/': typeof ProtectedChatsIndexRoute
  '/friends/': typeof ProtectedFriendsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/chats/$conversationId': typeof ProtectedChatsConversationIdRoute
  '/chats': typeof ProtectedChatsIndexRoute
  '/friends': typeof ProtectedFriendsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/_protected/chats/$conversationId': typeof ProtectedChatsConversationIdRoute
  '/_protected/chats/': typeof ProtectedChatsIndexRoute
  '/_protected/friends/': typeof ProtectedFriendsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/' | '/chats/$conversationId' | '/chats/' | '/friends/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/chats/$conversationId' | '/chats' | '/friends'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth/'
    | '/_protected/chats/$conversationId'
    | '/_protected/chats/'
    | '/_protected/friends/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/friends/': {
      id: '/_protected/friends/'
      path: '/friends'
      fullPath: '/friends/'
      preLoaderRoute: typeof ProtectedFriendsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chats/': {
      id: '/_protected/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ProtectedChatsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chats/$conversationId': {
      id: '/_protected/chats/$conversationId'
      path: '/chats/$conversationId'
      fullPath: '/chats/$conversationId'
      preLoaderRoute: typeof ProtectedChatsConversationIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedChatsConversationIdRoute: typeof ProtectedChatsConversationIdRoute
  ProtectedChatsIndexRoute: typeof ProtectedChatsIndexRoute
  ProtectedFriendsIndexRoute: typeof ProtectedFriendsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedChatsConversationIdRoute: ProtectedChatsConversationIdRoute,
  ProtectedChatsIndexRoute: ProtectedChatsIndexRoute,
  ProtectedFriendsIndexRoute: ProtectedFriendsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
